#!/usr/bin/env python3
"""Generate the packaged agent contract from the current prompt sources.

Run with --check to reject documentation drift without rewriting the file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PROMPTS = REPO / "packages" / "jaeger-agent" / "jaeger_agent" / "prompts"
DOC_PATH = REPO / "jaeger_ai" / "docs" / "agent_contract.md"


def render() -> str:
    # Read the source constants without importing a runtime or an instance.
    import ast
    tree = ast.parse((PROMPTS / "rules.py").read_text(encoding="utf-8"))
    rules = {
        target.id: ast.literal_eval(node.value)
        for node in tree.body if isinstance(node, ast.Assign)
        for target in node.targets if isinstance(target, ast.Name)
        and target.id.startswith("RUNTIME_TOOLSET_")
    }
    out = [
        "# Agent contract\n\n"
        "Generated by `dev/scripts/generate_agent_contract.py` from "
        "`packages/jaeger-agent/jaeger_agent/prompts/`. Do not hand-edit.\n\n"
        "These are the shared prompt sources. The final prompt also includes "
        "instance identity, tool schemas, runtime context, and one of the "
        "two toolset notes below.\n\n"
    ]
    sections = [(name, (PROMPTS / name).read_text(encoding="utf-8"))
                for name in ("framework_agent.md", "three_laws.md")]
    sections.extend(rules.items())
    for name, text in sections:
        out.append(f"## `{name}`\n\n````text\n{text.rstrip()}\n````\n\n")
    return "".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="generate_agent_contract")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the doc is stale (no write)")
    args = parser.parse_args(argv)

    fresh = render()
    if args.check:
        if not DOC_PATH.exists():
            sys.stderr.write(f"{DOC_PATH} missing — run the generator.\n")
            return 1
        on_disk = DOC_PATH.read_text(encoding="utf-8")
        if on_disk != fresh:
            sys.stderr.write(
                f"{DOC_PATH} is out of date — run "
                f"dev/scripts/generate_agent_contract.py to regenerate.\n"
            )
            return 1
        print(f"[agent_contract] {DOC_PATH.name}: up to date")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(fresh, encoding="utf-8")
    print(f"[agent_contract] wrote {DOC_PATH.relative_to(REPO)} "
          f"({len(fresh):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
